spring:
  application:
    name: Tech Books Explorer
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/tech_books_explorer?createDatabaseIfNotExist=true}
    username: ${DATABASE_USER:mysql}
    password: ${DATABASE_PASSWORD:mysql}
  jpa:
    show-sql: true
server:
  port: 80
