x-db-url: &DATABASE_URL jdbc:mysql://db:3306/tech_books_explorer?createDatabaseIfNotExist=true
x-db-user: &DATABASE_USER user
x-db-password: &DATABASE_PASSWORD password
x-db-name: &DATABASE_NAME tech_books_explorer

services:
  web:
    container_name: web_server
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    tty: true
    working_dir: /opt/app
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      DATABASE_URL: *DATABASE_URL
      DATABASE_USER: *DATABASE_USER
      DATABASE_PASSWORD: *DATABASE_PASSWORD
    volumes:
      - ..:/opt/app:delegated
    ports:
      - 8091:80
      - 8089:8089
    depends_on:
      - db

  db:
    container_name: db_server
    image: mysql:8.3
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: *DATABASE_USER
      MYSQL_PASSWORD: *DATABASE_PASSWORD
      MYSQL_DATABASE: *DATABASE_NAME
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true

  grafana:
    container_name: grafana
    image: grafana/grafana:11.6.0
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom-data:/prometheus

volumes:
  db-data:
  grafana-data:
  prom-data:
