name: Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cnb
        uses: buildpacks/github-actions/setup-pack@v5.8.8

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage --publishImage
        env:
          DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
          DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
